### ISSUE TITLE
Not work with python 3.2

### ISSUE THREAD

**Issue by StasTelnov** [jmcclell/django-bootstrap-pagination#39]
Collecting django-bootstrap-pagination
  Using cached django-bootstrap-pagination-1.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-ko5lpf/django-bootstrap-pagination/setup.py", line 13
        author=u'Jason McClellan',
                                ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ko5lpf/django-bootstrap-pagination

Explanation: http://stackoverflow.com/questions/8679985/unicode-strings-syntax-in-python

**Comment by jmcclell** [comment]
Truthfully, there is no official Python 3 support for this module. It's something I'd like to have but I just haven't done any Python work in quite a long while. It also seems like 3.2 might just be a dead version to this project given that they removed the feature and then added it right back in for 3.3 (because they likely realized how terrible of an idea it was to remove something like that in a point release!)

**Comment by StasTelnov** [comment]
Hell! :) Thank you for attention.
